### ISSUE TITLE
cannot compile properly

### ISSUE THREAD

**Issue by logicomyu** [vinsworldcom/NetCat64#1]
I am trying to compile it and I am getting bunch of errors like:

netcat64.c: In function `inet6_addr':
netcat64.c:306: warning: passing arg 1 of `WSAStringToAddressA' discards qualifiers from pointer target type
netcat64.c:306: warning: passing arg 4 of `WSAStringToAddressA' from incompatible pointer type
netcat64.c:306: warning: passing arg 5 of `WSAStringToAddressA' from incompatible pointer type
netcat64.c: In function `bail':
netcat64.c:456: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)
netcat64.c: In function `gethostpoop':
netcat64.c:687: warning: pointer type mismatch in conditional expression
netcat64.c: In function `GetAdapterPoop':
netcat64.c:897: error: `GAA_FLAG_SKIP_ANYCAST' undeclared (first use in this function)
netcat64.c:897: error: (Each undeclared identifier is reported only once
netcat64.c:897: error: for each function it appears in.)
netcat64.c:897: error: `GAA_FLAG_SKIP_MULTICAST' undeclared (first use in this function)
netcat64.c:897: error: `GAA_FLAG_SKIP_DNS_SERVER' undeclared (first use in this function)
netcat64.c:897: error: `GAA_FLAG_SKIP_FRIENDLY_NAME' undeclared (first use in this function)
netcat64.c:899: error: `PIP_ADAPTER_ADDRESSES' undeclared (first use in this function)
netcat64.c:899: error: syntax error before "pAddresses"
netcat64.c:901: error: `PIP_ADAPTER_UNICAST_ADDRESS' undeclared (first use in this function)
netcat64.c:906: error: `pAddresses' undeclared (first use in this function)
netcat64.c:906: error: `IP_ADAPTER_ADDRESSES' undeclared (first use in this function)
netcat64.c:906: error: syntax error before ')' token
netcat64.c:926: error: `pCurrAddresses' undeclared (first use in this function)
netcat64.c:929: error: `pUnicast' undeclared (first use in this function)
netcat64.c: In function `doconnect6':
netcat64.c:1152: error: `GROUP_SOURCE_REQ' undeclared (first use in this function)
netcat64.c:1152: error: syntax error before "mreq"
netcat64.c:1158: error: `mreq' undeclared (first use in this function)
netcat64.c:1213: warning: passing arg 2 of `bind' from incompatible pointer type
netcat64.c:1221: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)
netcat64.c:1313: warning: passing arg 2 of `connect' from incompatible pointer type
netcat64.c: In function `doconnect':
netcat64.c:1424: error: `IP_RECEIVE_BROADCAST' undeclared (first use in this function)
netcat64.c:1484: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)
netcat64.c: In function `dolisten6':
netcat64.c:1647: warning: passing arg 2 of `getsockname' from incompatible pointer type
netcat64.c:1689: warning: passing arg 5 of `recvfrom' from incompatible pointer type
netcat64.c:1718: warning: passing arg 2 of `connect' from incompatible pointer type
netcat64.c:1726: warning: passing arg 2 of `accept' from incompatible pointer type
netcat64.c:1795: warning: passing arg 2 of `getsockname' from incompatible pointer type
netcat64.c: In function `udptest6':
netcat64.c:2138: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)
netcat64.c: In function `udptest':
netcat64.c:2210: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)
netcat64.c: In function `readwrite':
netcat64.c:2487: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)
netcat64.c:2773: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)
netcat64.c: In function `main':
netcat64.c:3401: warning: `_sleep' is deprecated (declared at c:/MinGW/bin/../lib/gcc/mingw32/3.4.5/../../../../include/stdlib.h:395)

Once I managed to get nc64. exe with minigw make but it didn't worked at all.

Could you please provide instruction on how it should be compiled/changed for windows
 
I cannot find windows another version of netcat which allows multicast and multiple unicast connections to the same port. 

I would appreciate your help.

Regards.

**Comment by vinsworldcom** [comment]
See [releases](https://github.com/vinsworldcom/NetCat64/tree/1.11.6.4)
